[package]
name = "rmde"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.24.1"
markdown = "1.0.0-alpha.16"
rfd = "0.12.1"
ron = "0.8.1"
serde = "1.0.193"
